services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chess_simulator_php
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command: php -S 0.0.0.0:8000 -t public
